- hosts: ios_devices
  gather_facts: no
  connection: local

  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: IOS | Show etherchannel summary
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show etherchannel summary | in Po
    register: sum

  - debug: msg="{{ sum.stdout }}"
